[package]
name = "bgv-rust"
version = "0.1.0"
edition = "2021"

[dependencies]
num = "0.4"
num-bigint = { version = "0.4", features = ["rand"] }
num-traits = "0.2"
rand = "0.8"
rug = "1.16"
thiserror = "1.0"